### ISSUE TITLE
Solutions missing ident, blueprint yaml invalid

### ISSUE THREAD

**Issue by srlynch1** [grantorchard/cas-socialabs#77]
https://cas-socialabs.vmwapj.com/_solutions/cloud%20agnostic%20blueprint.html

missing space after Cloud_Machine_1

example
``` yaml
formatVersion: 1
inputs: {}
resources:
  Cloud_Machine_1:
  type: Cloud.Machine
  properties:
    image: 'ubuntu'
    flavor: 'medium'
    constraints:
      - tag: 'platform:aws'
```

shoud be

``` yaml
formatVersion: 1
inputs: {}
resources:
  Cloud_Machine_1:
   type: Cloud.Machine
   properties:
     image: 'ubuntu'
     flavor: 'medium'
     constraints:
      - tag: 'platform:aws'
```
